### PR TITLE
Add python-dev to travis.yaml

### PR DESCRIPTION
**Pull request by cawallin**

### CODE REVIEW

**Comment by arhimondr** [comment]
lgtm

**Comment by ebd2** [comment]
LGTM

**Comment by ArturGajowy** [comment]
Why is that needed? I've just run a [build on master branch without this change](https://travis-ci.org/Teradata/presto-checks/jobs/181670167) and it worked. Is there a failure log somewhere showing the need?

**Comment by ArturGajowy** [comment]
By "it worked" I mean "aws cli worked". I'm assuming the reason for this change from the branch name. But it seems to be unneeded.

**Comment by cawallin** [comment]
We were getting a pip install error: https://travis-ci.org/Teradata/presto-checks/jobs/177712024

**Pull request closed without merging**
